version: '3.8'

services:
  api:
    image: webofmars/todos-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: todo-api
    environment:
      DB_PATH: /root/data/todos.db
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - api_data:/root/data
    networks:
      - todo-network
    restart: unless-stopped

  frontend:
    image: webofmars/todos-front:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
      API_HOST: api
      API_PORT: 8080
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  api_data:

networks:
  todo-network:
    driver: bridge
